---

- name: Create the {{ app_name }} application
  hosts: appnodes
  become: yes
  become_user: root
  remote_user: root
  vars_files:
    - vars/base.yml
    - vars/app.yml
  roles:
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - base
    - app
    - deploy